name: Daily Newsletter Digest

on:
  schedule:
    - cron: '0 15 * * *' # 8am PST = 15:00 UTC
  workflow_dispatch:

jobs:
  digest:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run newsletter digest
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          TOKEN_JSON_B64: ${{ secrets.TOKEN_JSON_B64 }}
          GH_PAT: ${{ secrets.GH_PAT }}
          GITHUB_ACTIONS: true
        run: python summail_digest.py
