name: Daily Newsletter Digest

on:
  schedule:
    # Run daily at 5pm PST (1am UTC next day)
    - cron: '0 1 * * *'
  workflow_dispatch: # Allow manual triggering

jobs:
  digest:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Create service account key file
        run: echo '${{ secrets.SERVICE_ACCOUNT_KEY }}' > service-account-key.json

      - name: Run newsletter digest
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: python summail_digest.py
